<?php

/**
 * @file
 * Contains formcustomtemplate.module.
 */


/**
 * Implements hook_theme().
 */
function formcustomtemplate_theme() {
  return array(
    'form__my_form_test' => array(
      'render element' => 'form',
      'template' => 'form--myformtest-form',
      'base hook' => 'form',
    ),
  );
}

function formcustomtemplate_theme_registry_alter(&$theme_registry) {
 // dump($theme_registry); die();
}